### ISSUE TITLE
Symbol definition is void string_empty\?

### ISSUE THREAD

**Issue by wmealing** [cmpitg/wand#10]
Trying the first example and get the above message.

emacs-25.1-3.fc25.x86_64
wand-20170116.223/ (elpa)

**Comment by wmealing** [comment]
Nevermind, just found
https://github.com/cmpitg/wand/pull/9/commits/1b759b4729f55bf0a7cec1b525e86b1843cad940

**Comment by cmpitg** [comment]
Thanks for the heads-up. I have merged the PR and pushed another fix. Is it working for you now?

**Comment by wmealing** [comment]
Sorry, missed this original message, not sure why, and yes.
