### ISSUE TITLE
Could it be used without a selection?

### ISSUE THREAD

**Issue by casouri** [cmpitg/wand#11]
Is there going to be a command like `execute-at-point`?

**Comment by cmpitg** [comment]
Sorry it took ages for me to reply.  Though I use the extension on the daily basis, I have not been so active in maintaining it.  Now I intend be involved a bit more.

There could be a command like `execute-at-point`, though I don't know if such use case is strong.  Would you be seeing yourself using such command often?

In the mean time, it's very trivial to add a wrapper to `wand:execute` that takes the current `thing-at-point`, e.g.

```elisp
(defun* ~execute-thing-at-point (&optional (thing 'line))
  "Executes the current thing at point"
  (interactive)
  (require 'thingatpt)
  (wand:execute (thing-at-point thing)))
```

Hope this helps!

**Comment by casouri** [comment]
Thanks, this should work :-)
